// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/api_key/consumer.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/api_key/consumer.proto.
 */
export const file_gargauth_auth_v1_api_key_consumer: GenFile = /*@__PURE__*/
  fileDesc("CidnYXJnYXV0aC9hdXRoL3YxL2FwaV9rZXkvY29uc3VtZXIucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEifwoIQ29uc3VtZXISCwoDdWlkGAEgASgMEioKBmlzc3VlZBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoGZXhwaXJ5GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBQgkKB19leHBpcnlChwEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQg1Db25zdW1lclByb3RvUAGiAgNHQViqAhBHYXJnYXV0aC5BdXRoLlYxygIQR2FyZ2F1dGhcQXV0aFxWMeICHEdhcmdhdXRoXEF1dGhcVjFcR1BCTWV0YWRhdGHqAhJHYXJnYXV0aDo6QXV0aDo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message gargauth.auth.v1.Consumer
 */
export type Consumer = Message<"gargauth.auth.v1.Consumer"> & {
  /**
   * @generated from field: bytes uid = 1;
   */
  uid: Uint8Array;

  /**
   * @generated from field: google.protobuf.Timestamp issued = 2;
   */
  issued?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp expiry = 3;
   */
  expiry?: Timestamp;
};

/**
 * Describes the message gargauth.auth.v1.Consumer.
 * Use `create(ConsumerSchema)` to create a new message.
 */
export const ConsumerSchema: GenMessage<Consumer> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_api_key_consumer, 0);

