// @generated by protoc-gen-es v2.1.0
// @generated from file gargauth/auth/v1/auth_failure.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/auth_failure.proto.
 */
export declare const file_gargauth_auth_v1_auth_failure: GenFile;

/**
 * @generated from message gargauth.auth.v1.AuthFailure
 */
export declare type AuthFailure = Message<"gargauth.auth.v1.AuthFailure"> & {
};

/**
 * Describes the message gargauth.auth.v1.AuthFailure.
 * Use `create(AuthFailureSchema)` to create a new message.
 */
export declare const AuthFailureSchema: GenMessage<AuthFailure>;

