// @generated by protoc-gen-es v2.1.0 with parameter "target=dts"
// @generated from file gargauth/auth/v1/auth_successful.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/auth_successful.proto.
 */
export declare const file_gargauth_auth_v1_auth_successful: GenFile;

/**
 * @generated from message gargauth.auth.v1.AuthSuccessful
 */
export declare type AuthSuccessful = Message<"gargauth.auth.v1.AuthSuccessful"> & {
};

/**
 * Describes the message gargauth.auth.v1.AuthSuccessful.
 * Use `create(AuthSuccessfulSchema)` to create a new message.
 */
export declare const AuthSuccessfulSchema: GenMessage<AuthSuccessful>;

