// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/init/client_init_success.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/init/client_init_success.proto.
 */
export const file_gargauth_auth_v1_init_client_init_success: GenFile = /*@__PURE__*/
  fileDesc("Ci9nYXJnYXV0aC9hdXRoL3YxL2luaXQvY2xpZW50X2luaXRfc3VjY2Vzcy5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSIkChFDbGllbnRJbml0U3VjY2VzcxIPCgdwYXlsb2FkGAEgASgMQpABChRjb20uZ2FyZ2F1dGguYXV0aC52MUIWQ2xpZW50SW5pdFN1Y2Nlc3NQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM");

/**
 * @generated from message gargauth.auth.v1.ClientInitSuccess
 */
export type ClientInitSuccess = Message<"gargauth.auth.v1.ClientInitSuccess"> & {
  /**
   * @generated from field: bytes payload = 1;
   */
  payload: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.ClientInitSuccess.
 * Use `create(ClientInitSuccessSchema)` to create a new message.
 */
export const ClientInitSuccessSchema: GenMessage<ClientInitSuccess> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_init_client_init_success, 0);

