"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/init/client_init_success.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientInitSuccessSchema = exports.file_gargauth_auth_v1_init_client_init_success = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/init/client_init_success.proto.
 */
exports.file_gargauth_auth_v1_init_client_init_success = (0, codegenv1_1.fileDesc)("Ci9nYXJnYXV0aC9hdXRoL3YxL2luaXQvY2xpZW50X2luaXRfc3VjY2Vzcy5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSIkChFDbGllbnRJbml0U3VjY2VzcxIPCgdwYXlsb2FkGAEgASgMQpABChRjb20uZ2FyZ2F1dGguYXV0aC52MUIWQ2xpZW50SW5pdFN1Y2Nlc3NQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM");
/**
 * Describes the message gargauth.auth.v1.ClientInitSuccess.
 * Use `create(ClientInitSuccessSchema)` to create a new message.
 */
exports.ClientInitSuccessSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_init_client_init_success, 0);
