"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/consumer/consumer_auth_successful.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConsumerAuthSuccessfulSchema = exports.file_gargauth_auth_v1_consumer_consumer_auth_successful = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/consumer/consumer_auth_successful.proto.
 */
exports.file_gargauth_auth_v1_consumer_consumer_auth_successful = (0, codegenv1_1.fileDesc)("CjhnYXJnYXV0aC9hdXRoL3YxL2NvbnN1bWVyL2NvbnN1bWVyX2F1dGhfc3VjY2Vzc2Z1bC5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSIYChZDb25zdW1lckF1dGhTdWNjZXNzZnVsQpUBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIbQ29uc3VtZXJBdXRoU3VjY2Vzc2Z1bFByb3RvUAGiAgNHQViqAhBHYXJnYXV0aC5BdXRoLlYxygIQR2FyZ2F1dGhcQXV0aFxWMeICHEdhcmdhdXRoXEF1dGhcVjFcR1BCTWV0YWRhdGHqAhJHYXJnYXV0aDo6QXV0aDo6VjFiBnByb3RvMw");
/**
 * Describes the message gargauth.auth.v1.ConsumerAuthSuccessful.
 * Use `create(ConsumerAuthSuccessfulSchema)` to create a new message.
 */
exports.ConsumerAuthSuccessfulSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_consumer_consumer_auth_successful, 0);
