// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/consumer/consumer_auth_failure.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/consumer/consumer_auth_failure.proto.
 */
export const file_gargauth_auth_v1_consumer_consumer_auth_failure: GenFile = /*@__PURE__*/
  fileDesc("CjVnYXJnYXV0aC9hdXRoL3YxL2NvbnN1bWVyL2NvbnN1bWVyX2F1dGhfZmFpbHVyZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSIVChNDb25zdW1lckF1dGhGYWlsdXJlQpIBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIYQ29uc3VtZXJBdXRoRmFpbHVyZVByb3RvUAGiAgNHQViqAhBHYXJnYXV0aC5BdXRoLlYxygIQR2FyZ2F1dGhcQXV0aFxWMeICHEdhcmdhdXRoXEF1dGhcVjFcR1BCTWV0YWRhdGHqAhJHYXJnYXV0aDo6QXV0aDo6VjFiBnByb3RvMw");

/**
 * @generated from message gargauth.auth.v1.ConsumerAuthFailure
 */
export type ConsumerAuthFailure = Message<"gargauth.auth.v1.ConsumerAuthFailure"> & {
};

/**
 * Describes the message gargauth.auth.v1.ConsumerAuthFailure.
 * Use `create(ConsumerAuthFailureSchema)` to create a new message.
 */
export const ConsumerAuthFailureSchema: GenMessage<ConsumerAuthFailure> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_consumer_consumer_auth_failure, 0);

