<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/api_key.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class ApiKey
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB3\x02\x0A\x1Egargauth/auth/v1/api_key.proto\x12\x10gargauth.auth.v1\"o\x0A\x06ApiKey\x12\x16\x0A\x06client\x18\x01 \x01(\x0CR\x06client\x12\x15\x0A\x06key_id\x18\x02 \x01(\x0CR\x05keyId\x12\x18\x0A\x07payload\x18\x03 \x01(\x0CR\x07payload\x12\x1C\x0A\x09signature\x18\x04 \x01(\x0CR\x09signatureB\x85\x01\x0A\x14com.gargauth.auth.v1B\x0BApiKeyProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

