<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/authenticate_consumer.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class AuthenticateConsumer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\AuthRequest::initOnce();
        \Gargauth\Auth\V1\GPBMetadata\AuthResponse::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF2\x02\x0A,gargauth/auth/v1/authenticate_consumer.proto\x12\x10gargauth.auth.v1\x1A\$gargauth/auth/v1/auth_response.proto2l\x0A\x1BAuthenticateConsumerService\x12M\x0A\x0Cauthenticate\x12\x1D.gargauth.auth.v1.AuthRequest\x1A\x1E.gargauth.auth.v1.AuthResponseB\x93\x01\x0A\x14com.gargauth.auth.v1B\x19AuthenticateConsumerProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

