<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/authenticate_consumer_response.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class AuthenticateConsumerResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\ConsumerAuthSuccessful::initOnce();
        \Gargauth\Auth\V1\GPBMetadata\ConsumerAuthFailure::initOnce();
        \Gargauth\Auth\V1\GPBMetadata\Correlation::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBF\x04\x0A5gargauth/auth/v1/authenticate_consumer_response.proto\x12\x10gargauth.auth.v1\x1A5gargauth/auth/v1/consumer/consumer_auth_failure.proto\x1A\"gargauth/auth/v1/correlation.proto\"\xF2\x01\x0A\x1CAuthenticateConsumerResponse\x12?\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1D.gargauth.auth.v1.CorrelationR\x0Bcorrelation\x12D\x0A\x07success\x18\x02 \x01(\x0B2(.gargauth.auth.v1.ConsumerAuthSuccessfulH\x00R\x07success\x12A\x0A\x07failure\x18\x03 \x01(\x0B2%.gargauth.auth.v1.ConsumerAuthFailureH\x00R\x07failureB\x08\x0A\x06resultB\x9B\x01\x0A\x14com.gargauth.auth.v1B!AuthenticateConsumerResponseProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

