<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/auth_failure.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class AuthFailure
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xDB\x01\x0A#gargauth/auth/v1/auth_failure.proto\x12\x10gargauth.auth.v1\"\x0D\x0A\x0BAuthFailureB\x8A\x01\x0A\x14com.gargauth.auth.v1B\x10AuthFailureProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

