<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/authenticate_consumer_request.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class AuthRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\Correlation::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8A\x03\x0A#gargauth/auth/v1/authenticate_consumer_request.proto\x12\x10gargauth.auth.v1\"\xBB\x01\x0A\x0BAuthRequest\x12?\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1D.gargauth.auth.v1.CorrelationR\x0Bcorrelation\x12\x15\x0A\x06key_id\x18\x02 \x01(\x0CR\x05keyId\x12\x1B\x0A\x09client_id\x18\x03 \x01(\x0CR\x08clientId\x12\x1D\x0A\x0Apublic_key\x18\x04 \x01(\x0CR\x09publicKey\x12\x18\x0A\x07payload\x18\x05 \x01(\x0CR\x07payloadB\x8A\x01\x0A\x14com.gargauth.auth.v1B\x10AuthRequestProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

