<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class Client
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\Correlation::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x02\x0A\x1Dgargauth/auth/v1/client.proto\x12\x10gargauth.auth.v1\"\x83\x01\x0A\x06Client\x12\x10\x0A\x03uid\x18\x01 \x01(\x0CR\x03uid\x12\x0E\x0A\x02iv\x18\x02 \x01(\x0CR\x02iv\x12\x16\x0A\x06secret\x18\x03 \x01(\x0CR\x06secret\x12?\x0A\x0Bcorrelation\x18\x04 \x01(\x0B2\x1D.gargauth.auth.v1.CorrelationR\x0BcorrelationB\x85\x01\x0A\x14com.gargauth.auth.v1B\x0BClientProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

