<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/init/client_init_success.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class ClientInitSuccess
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8D\x02\x0A/gargauth/auth/v1/init/client_init_success.proto\x12\x10gargauth.auth.v1\"-\x0A\x11ClientInitSuccess\x12\x18\x0A\x07payload\x18\x01 \x01(\x0CR\x07payloadB\x90\x01\x0A\x14com.gargauth.auth.v1B\x16ClientInitSuccessProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

