<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client_init_response.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class ClientInitResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\Correlation::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB2\x02\x0A+gargauth/auth/v1/client_init_response.proto\x12\x10gargauth.auth.v1\"U\x0A\x12ClientInitResponse\x12?\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1D.gargauth.auth.v1.CorrelationR\x0BcorrelationB\x91\x01\x0A\x14com.gargauth.auth.v1B\x17ClientInitResponseProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

