<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client_init_request.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class ClientInitRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\Client::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBA\x02\x0A*gargauth/auth/v1/client_init_request.proto\x12\x10gargauth.auth.v1\"_\x0A\x11ClientInitRequest\x120\x0A\x06client\x18\x01 \x01(\x0B2\x18.gargauth.auth.v1.ClientR\x06client\x12\x18\x0A\x07payload\x18\x02 \x01(\x0CR\x07payloadB\x90\x01\x0A\x14com.gargauth.auth.v1B\x16ClientInitRequestProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

