<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/api_key/consumer.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class Consumer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE4\x02\x0A'gargauth/auth/v1/api_key/consumer.proto\x12\x10gargauth.auth.v1\"\x94\x01\x0A\x08Consumer\x12\x10\x0A\x03uid\x18\x01 \x01(\x0CR\x03uid\x122\x0A\x06issued\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x06issued\x127\x0A\x06expiry\x18\x03 \x01(\x0B2\x1A.google.protobuf.TimestampH\x00R\x06expiry\x88\x01\x01B\x09\x0A\x07_expiryB\x87\x01\x0A\x14com.gargauth.auth.v1B\x0DConsumerProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

