<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/init_client.proto

namespace Gargauth\Auth\V1\GPBMetadata;

class InitClient
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gargauth\Auth\V1\GPBMetadata\ClientInitRequest::initOnce();
        \Gargauth\Auth\V1\GPBMetadata\ClientInitResponse::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x02\x0A\"gargauth/auth/v1/init_client.proto\x12\x10gargauth.auth.v1\x1A+gargauth/auth/v1/client_init_response.proto2n\x0A\x11InitClientService\x12Y\x0A\x0Cauthenticate\x12#.gargauth.auth.v1.ClientInitRequest\x1A\$.gargauth.auth.v1.ClientInitResponseB\x89\x01\x0A\x14com.gargauth.auth.v1B\x0FInitClientProtoP\x01\xA2\x02\x03GAX\xAA\x02\x10Gargauth.Auth.V1\xCA\x02\x10Gargauth\\Auth\\V1\xE2\x02\x1CGargauth\\Auth\\V1\\GPBMetadata\xEA\x02\x12Gargauth::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

