<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/api_key.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.ApiKey</code>
 */
class ApiKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes client = 1 [json_name = "client"];</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     */
    protected $key_id = '';
    /**
     * Generated from protobuf field <code>bytes payload = 3 [json_name = "payload"];</code>
     */
    protected $payload = '';
    /**
     * Generated from protobuf field <code>bytes signature = 4 [json_name = "signature"];</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client
     *     @type string $key_id
     *     @type string $payload
     *     @type string $signature
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\ApiKey::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes client = 1 [json_name = "client"];</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>bytes client = 1 [json_name = "client"];</code>
     * @param string $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkString($var, False);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, False);
        $this->key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3 [json_name = "payload"];</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3 [json_name = "payload"];</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4 [json_name = "signature"];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4 [json_name = "signature"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

