<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/authenticate_consumer_request.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.AuthRequest</code>
 */
class AuthRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     */
    protected $correlation = null;
    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     */
    protected $key_id = '';
    /**
     * Generated from protobuf field <code>bytes client_id = 3 [json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>bytes public_key = 4 [json_name = "publicKey"];</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>bytes payload = 5 [json_name = "payload"];</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Gargauth\Auth\V1\Correlation $correlation
     *     @type string $key_id
     *     @type string $client_id
     *     @type string $public_key
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\AuthRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @return \Gargauth\Auth\V1\Correlation|null
     */
    public function getCorrelation()
    {
        return $this->correlation;
    }

    public function hasCorrelation()
    {
        return isset($this->correlation);
    }

    public function clearCorrelation()
    {
        unset($this->correlation);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @param \Gargauth\Auth\V1\Correlation $var
     * @return $this
     */
    public function setCorrelation($var)
    {
        GPBUtil::checkMessage($var, \Gargauth\Auth\V1\Correlation::class);
        $this->correlation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * Generated from protobuf field <code>bytes key_id = 2 [json_name = "keyId"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, False);
        $this->key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes client_id = 3 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>bytes client_id = 3 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 4 [json_name = "publicKey"];</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 4 [json_name = "publicKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 5 [json_name = "payload"];</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 5 [json_name = "payload"];</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

