<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client_init_request.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.ClientInitRequest</code>
 */
class ClientInitRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Client client = 1 [json_name = "client"];</code>
     */
    protected $client = null;
    /**
     * Generated from protobuf field <code>bytes payload = 2 [json_name = "payload"];</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Gargauth\Auth\V1\Client $client
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\ClientInitRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Client client = 1 [json_name = "client"];</code>
     * @return \Gargauth\Auth\V1\Client|null
     */
    public function getClient()
    {
        return $this->client;
    }

    public function hasClient()
    {
        return isset($this->client);
    }

    public function clearClient()
    {
        unset($this->client);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Client client = 1 [json_name = "client"];</code>
     * @param \Gargauth\Auth\V1\Client $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkMessage($var, \Gargauth\Auth\V1\Client::class);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 2 [json_name = "payload"];</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 2 [json_name = "payload"];</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

