<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client_init_response.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.ClientInitResponse</code>
 */
class ClientInitResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     */
    protected $correlation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Gargauth\Auth\V1\Correlation $correlation
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\ClientInitResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @return \Gargauth\Auth\V1\Correlation|null
     */
    public function getCorrelation()
    {
        return $this->correlation;
    }

    public function hasCorrelation()
    {
        return isset($this->correlation);
    }

    public function clearCorrelation()
    {
        unset($this->correlation);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @param \Gargauth\Auth\V1\Correlation $var
     * @return $this
     */
    public function setCorrelation($var)
    {
        GPBUtil::checkMessage($var, \Gargauth\Auth\V1\Correlation::class);
        $this->correlation = $var;

        return $this;
    }

}

