<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/client.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.Client</code>
 */
class Client extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>bytes iv = 2 [json_name = "iv"];</code>
     */
    protected $iv = '';
    /**
     * Generated from protobuf field <code>bytes secret = 3 [json_name = "secret"];</code>
     */
    protected $secret = '';
    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 4 [json_name = "correlation"];</code>
     */
    protected $correlation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *     @type string $iv
     *     @type string $secret
     *     @type \Gargauth\Auth\V1\Correlation $correlation
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2 [json_name = "iv"];</code>
     * @return string
     */
    public function getIv()
    {
        return $this->iv;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2 [json_name = "iv"];</code>
     * @param string $var
     * @return $this
     */
    public function setIv($var)
    {
        GPBUtil::checkString($var, False);
        $this->iv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes secret = 3 [json_name = "secret"];</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Generated from protobuf field <code>bytes secret = 3 [json_name = "secret"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, False);
        $this->secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 4 [json_name = "correlation"];</code>
     * @return \Gargauth\Auth\V1\Correlation|null
     */
    public function getCorrelation()
    {
        return $this->correlation;
    }

    public function hasCorrelation()
    {
        return isset($this->correlation);
    }

    public function clearCorrelation()
    {
        unset($this->correlation);
    }

    /**
     * Generated from protobuf field <code>.gargauth.auth.v1.Correlation correlation = 4 [json_name = "correlation"];</code>
     * @param \Gargauth\Auth\V1\Correlation $var
     * @return $this
     */
    public function setCorrelation($var)
    {
        GPBUtil::checkMessage($var, \Gargauth\Auth\V1\Correlation::class);
        $this->correlation = $var;

        return $this;
    }

}

