<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/api_key/consumer.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.Consumer</code>
 */
class Consumer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp issued = 2 [json_name = "issued"];</code>
     */
    protected $issued = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp expiry = 3 [json_name = "expiry"];</code>
     */
    protected $expiry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *     @type \Google\Protobuf\Timestamp $issued
     *     @type \Google\Protobuf\Timestamp $expiry
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\Consumer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp issued = 2 [json_name = "issued"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIssued()
    {
        return $this->issued;
    }

    public function hasIssued()
    {
        return isset($this->issued);
    }

    public function clearIssued()
    {
        unset($this->issued);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp issued = 2 [json_name = "issued"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIssued($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->issued = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp expiry = 3 [json_name = "expiry"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getExpiry()
    {
        return $this->expiry;
    }

    public function hasExpiry()
    {
        return isset($this->expiry);
    }

    public function clearExpiry()
    {
        unset($this->expiry);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp expiry = 3 [json_name = "expiry"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExpiry($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->expiry = $var;

        return $this;
    }

}

