<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gargauth/auth/v1/correlation.proto

namespace Gargauth\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gargauth.auth.v1.Correlation</code>
 */
class Correlation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     */
    protected $uid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     * }
     */
    public function __construct($data = NULL) {
        \Gargauth\Auth\V1\GPBMetadata\Correlation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>bytes uid = 1 [json_name = "uid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, False);
        $this->uid = $var;

        return $this;
    }

}

