<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: gargauth/auth/v1/init_client.proto

namespace Gargauth\Auth\V1;

use Spiral\RoadRunner\GRPC;

interface InitClientServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "gargauth.auth.v1.InitClientService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ClientInitRequest $in
    * @return ClientInitResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function authenticate(GRPC\ContextInterface $ctx, ClientInitRequest $in): ClientInitResponse;
}
