"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticateConsumerService = exports.file_gargauth_auth_v1_authenticate_consumer = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const authenticate_consumer_request_pb_1 = require("./authenticate_consumer_request_pb");
const authenticate_consumer_response_pb_1 = require("./authenticate_consumer_response_pb");
/**
 * Describes the file gargauth/auth/v1/authenticate_consumer.proto.
 */
exports.file_gargauth_auth_v1_authenticate_consumer = (0, codegenv1_1.fileDesc)("CixnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lci5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MTKMAQobQXV0aGVudGljYXRlQ29uc3VtZXJTZXJ2aWNlEm0KDGF1dGhlbnRpY2F0ZRItLmdhcmdhdXRoLmF1dGgudjEuQXV0aGVudGljYXRlQ29uc3VtZXJSZXF1ZXN0Gi4uZ2FyZ2F1dGguYXV0aC52MS5BdXRoZW50aWNhdGVDb25zdW1lclJlc3BvbnNlQpMBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIZQXV0aGVudGljYXRlQ29uc3VtZXJQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [authenticate_consumer_request_pb_1.file_gargauth_auth_v1_authenticate_consumer_request, authenticate_consumer_response_pb_1.file_gargauth_auth_v1_authenticate_consumer_response]);
/**
 * @generated from service gargauth.auth.v1.AuthenticateConsumerService
 */
exports.AuthenticateConsumerService = (0, codegenv1_1.serviceDesc)(exports.file_gargauth_auth_v1_authenticate_consumer, 0);
