"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticateConsumerRequestSchema = exports.file_gargauth_auth_v1_authenticate_consumer_request = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const client_pb_1 = require("./client_pb");
/**
 * Describes the file gargauth/auth/v1/authenticate_consumer_request.proto.
 */
exports.file_gargauth_auth_v1_authenticate_consumer_request = (0, codegenv1_1.fileDesc)("CjRnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lcl9yZXF1ZXN0LnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIlgKG0F1dGhlbnRpY2F0ZUNvbnN1bWVyUmVxdWVzdBIoCgZjbGllbnQYASABKAsyGC5nYXJnYXV0aC5hdXRoLnYxLkNsaWVudBIPCgdwYXlsb2FkGAIgASgMQpoBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIgQXV0aGVudGljYXRlQ29uc3VtZXJSZXF1ZXN0UHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [client_pb_1.file_gargauth_auth_v1_client]);
/**
 * Describes the message gargauth.auth.v1.AuthenticateConsumerRequest.
 * Use `create(AuthenticateConsumerRequestSchema)` to create a new message.
 */
exports.AuthenticateConsumerRequestSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_authenticate_consumer_request, 0);
