// @generated by protoc-gen-es v2.1.0
// @generated from file gargauth/auth/v1/auth_failure.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file gargauth/auth/v1/auth_failure.proto.
 */
export const file_gargauth_auth_v1_auth_failure = /*@__PURE__*/
  fileDesc("CiNnYXJnYXV0aC9hdXRoL3YxL2F1dGhfZmFpbHVyZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSINCgtBdXRoRmFpbHVyZUKKAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEEF1dGhGYWlsdXJlUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");

/**
 * Describes the message gargauth.auth.v1.AuthFailure.
 * Use `create(AuthFailureSchema)` to create a new message.
 */
export const AuthFailureSchema = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_auth_failure, 0);

