"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/client.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientSchema = exports.file_gargauth_auth_v1_client = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const correlation_pb_1 = require("./correlation_pb");
/**
 * Describes the file gargauth/auth/v1/client.proto.
 */
exports.file_gargauth_auth_v1_client = (0, codegenv1_1.fileDesc)("Ch1nYXJnYXV0aC9hdXRoL3YxL2NsaWVudC5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSJlCgZDbGllbnQSCwoDdWlkGAEgASgMEgoKAml2GAIgASgMEg4KBnNlY3JldBgDIAEoDBIyCgtjb3JyZWxhdGlvbhgEIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb25ChQEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQgtDbGllbnRQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [correlation_pb_1.file_gargauth_auth_v1_correlation]);
/**
 * Describes the message gargauth.auth.v1.Client.
 * Use `create(ClientSchema)` to create a new message.
 */
exports.ClientSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_client, 0);
