"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/client_init_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientInitRequestSchema = exports.file_gargauth_auth_v1_client_init_request = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const client_pb_1 = require("./client_pb");
/**
 * Describes the file gargauth/auth/v1/client_init_request.proto.
 */
exports.file_gargauth_auth_v1_client_init_request = (0, codegenv1_1.fileDesc)("CipnYXJnYXV0aC9hdXRoL3YxL2NsaWVudF9pbml0X3JlcXVlc3QucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEiTgoRQ2xpZW50SW5pdFJlcXVlc3QSKAoGY2xpZW50GAEgASgLMhguZ2FyZ2F1dGguYXV0aC52MS5DbGllbnQSDwoHcGF5bG9hZBgCIAEoDEKQAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCFkNsaWVudEluaXRSZXF1ZXN0UHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [client_pb_1.file_gargauth_auth_v1_client]);
/**
 * Describes the message gargauth.auth.v1.ClientInitRequest.
 * Use `create(ClientInitRequestSchema)` to create a new message.
 */
exports.ClientInitRequestSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_client_init_request, 0);
