"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/client_init_response.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientInitResponseSchema = exports.file_gargauth_auth_v1_client_init_response = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const correlation_pb_1 = require("./correlation_pb");
/**
 * Describes the file gargauth/auth/v1/client_init_response.proto.
 */
exports.file_gargauth_auth_v1_client_init_response = (0, codegenv1_1.fileDesc)("CitnYXJnYXV0aC9hdXRoL3YxL2NsaWVudF9pbml0X3Jlc3BvbnNlLnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIkgKEkNsaWVudEluaXRSZXNwb25zZRIyCgtjb3JyZWxhdGlvbhgBIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb25CkQEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQhdDbGllbnRJbml0UmVzcG9uc2VQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [correlation_pb_1.file_gargauth_auth_v1_correlation]);
/**
 * Describes the message gargauth.auth.v1.ClientInitResponse.
 * Use `create(ClientInitResponseSchema)` to create a new message.
 */
exports.ClientInitResponseSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_client_init_response, 0);
