"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/api_key/consumer.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConsumerSchema = exports.file_gargauth_auth_v1_api_key_consumer = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
const wkt_1 = require("@bufbuild/protobuf/wkt");
/**
 * Describes the file gargauth/auth/v1/api_key/consumer.proto.
 */
exports.file_gargauth_auth_v1_api_key_consumer = (0, codegenv1_1.fileDesc)("CidnYXJnYXV0aC9hdXRoL3YxL2FwaV9rZXkvY29uc3VtZXIucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEifwoIQ29uc3VtZXISCwoDdWlkGAEgASgMEioKBmlzc3VlZBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoGZXhwaXJ5GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBQgkKB19leHBpcnlChwEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQg1Db25zdW1lclByb3RvUAGiAgNHQViqAhBHYXJnYXV0aC5BdXRoLlYxygIQR2FyZ2F1dGhcQXV0aFxWMeICHEdhcmdhdXRoXEF1dGhcVjFcR1BCTWV0YWRhdGHqAhJHYXJnYXV0aDo6QXV0aDo6VjFiBnByb3RvMw", [wkt_1.file_google_protobuf_timestamp]);
/**
 * Describes the message gargauth.auth.v1.Consumer.
 * Use `create(ConsumerSchema)` to create a new message.
 */
exports.ConsumerSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_api_key_consumer, 0);
