"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/api_key.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiKeySchema = exports.file_gargauth_auth_v1_api_key = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/api_key.proto.
 */
exports.file_gargauth_auth_v1_api_key = (0, codegenv1_1.fileDesc)("Ch5nYXJnYXV0aC9hdXRoL3YxL2FwaV9rZXkucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEiTAoGQXBpS2V5Eg4KBmNsaWVudBgBIAEoDBIOCgZrZXlfaWQYAiABKAwSDwoHcGF5bG9hZBgDIAEoDBIRCglzaWduYXR1cmUYBCABKAxChQEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQgtBcGlLZXlQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM");
/**
 * Describes the message gargauth.auth.v1.ApiKey.
 * Use `create(ApiKeySchema)` to create a new message.
 */
exports.ApiKeySchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_api_key, 0);
