// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/api_key.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/api_key.proto.
 */
export const file_gargauth_auth_v1_api_key: GenFile = /*@__PURE__*/
  fileDesc("Ch5nYXJnYXV0aC9hdXRoL3YxL2FwaV9rZXkucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEiTAoGQXBpS2V5Eg4KBmNsaWVudBgBIAEoDBIOCgZrZXlfaWQYAiABKAwSDwoHcGF5bG9hZBgDIAEoDBIRCglzaWduYXR1cmUYBCABKAxChQEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQgtBcGlLZXlQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM");

/**
 * @generated from message gargauth.auth.v1.ApiKey
 */
export type ApiKey = Message<"gargauth.auth.v1.ApiKey"> & {
  /**
   * @generated from field: bytes client = 1;
   */
  client: Uint8Array;

  /**
   * @generated from field: bytes key_id = 2;
   */
  keyId: Uint8Array;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;

  /**
   * @generated from field: bytes signature = 4;
   */
  signature: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.ApiKey.
 * Use `create(ApiKeySchema)` to create a new message.
 */
export const ApiKeySchema: GenMessage<ApiKey> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_api_key, 0);

