"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_successful.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthSuccessfulSchema = exports.file_gargauth_auth_v1_auth_successful = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/auth_successful.proto.
 */
exports.file_gargauth_auth_v1_auth_successful = (0, codegenv1_1.fileDesc)("CiZnYXJnYXV0aC9hdXRoL3YxL2F1dGhfc3VjY2Vzc2Z1bC5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSIQCg5BdXRoU3VjY2Vzc2Z1bEKNAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCE0F1dGhTdWNjZXNzZnVsUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");
/**
 * Describes the message gargauth.auth.v1.AuthSuccessful.
 * Use `create(AuthSuccessfulSchema)` to create a new message.
 */
exports.AuthSuccessfulSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_auth_successful, 0);
