"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthRequestSchema = exports.file_gargauth_auth_v1_auth_request = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
var correlation_pb_1 = require("./correlation_pb");
/**
 * Describes the file gargauth/auth/v1/auth_request.proto.
 */
exports.file_gargauth_auth_v1_auth_request = (0, codegenv1_1.fileDesc)("CiNnYXJnYXV0aC9hdXRoL3YxL2F1dGhfcmVxdWVzdC5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSKJAQoLQXV0aFJlcXVlc3QSMgoLY29ycmVsYXRpb24YASABKAsyHS5nYXJnYXV0aC5hdXRoLnYxLkNvcnJlbGF0aW9uEg4KBmtleV9pZBgCIAEoDBIRCgljbGllbnRfaWQYAyABKAwSEgoKcHVibGljX2tleRgEIAEoDBIPCgdwYXlsb2FkGAUgASgMQooBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIQQXV0aFJlcXVlc3RQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [correlation_pb_1.file_gargauth_auth_v1_correlation]);
/**
 * Describes the message gargauth.auth.v1.AuthRequest.
 * Use `create(AuthRequestSchema)` to create a new message.
 */
exports.AuthRequestSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_auth_request, 0);
