"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticateConsumerService = exports.file_gargauth_auth_v1_authenticate_consumer = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
var auth_request_pb_1 = require("./auth_request_pb");
var auth_response_pb_1 = require("./auth_response_pb");
/**
 * Describes the file gargauth/auth/v1/authenticate_consumer.proto.
 */
exports.file_gargauth_auth_v1_authenticate_consumer = (0, codegenv1_1.fileDesc)("CixnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lci5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MTJsChtBdXRoZW50aWNhdGVDb25zdW1lclNlcnZpY2USTQoMYXV0aGVudGljYXRlEh0uZ2FyZ2F1dGguYXV0aC52MS5BdXRoUmVxdWVzdBoeLmdhcmdhdXRoLmF1dGgudjEuQXV0aFJlc3BvbnNlQpMBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIZQXV0aGVudGljYXRlQ29uc3VtZXJQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [auth_request_pb_1.file_gargauth_auth_v1_auth_request, auth_response_pb_1.file_gargauth_auth_v1_auth_response]);
/**
 * @generated from service gargauth.auth.v1.AuthenticateConsumerService
 */
exports.AuthenticateConsumerService = (0, codegenv1_1.serviceDesc)(exports.file_gargauth_auth_v1_authenticate_consumer, 0);
