// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_response.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { AuthSuccessful } from "./auth_successful_pb";
import { file_gargauth_auth_v1_auth_successful } from "./auth_successful_pb";
import type { AuthFailure } from "./auth_failure_pb";
import { file_gargauth_auth_v1_auth_failure } from "./auth_failure_pb";
import type { Correlation } from "./correlation_pb";
import { file_gargauth_auth_v1_correlation } from "./correlation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/auth_response.proto.
 */
export const file_gargauth_auth_v1_auth_response: GenFile = /*@__PURE__*/
  fileDesc("CiRnYXJnYXV0aC9hdXRoL3YxL2F1dGhfcmVzcG9uc2UucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEiswEKDEF1dGhSZXNwb25zZRIyCgtjb3JyZWxhdGlvbhgBIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb24SMwoHc3VjY2VzcxgCIAEoCzIgLmdhcmdhdXRoLmF1dGgudjEuQXV0aFN1Y2Nlc3NmdWxIABIwCgdmYWlsdXJlGAMgASgLMh0uZ2FyZ2F1dGguYXV0aC52MS5BdXRoRmFpbHVyZUgAQggKBnJlc3VsdEKLAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEUF1dGhSZXNwb25zZVByb3RvUAGiAgNHQViqAhBHYXJnYXV0aC5BdXRoLlYxygIQR2FyZ2F1dGhcQXV0aFxWMeICHEdhcmdhdXRoXEF1dGhcVjFcR1BCTWV0YWRhdGHqAhJHYXJnYXV0aDo6QXV0aDo6VjFiBnByb3RvMw", [file_gargauth_auth_v1_auth_successful, file_gargauth_auth_v1_auth_failure, file_gargauth_auth_v1_correlation]);

/**
 * @generated from message gargauth.auth.v1.AuthResponse
 */
export type AuthResponse = Message<"gargauth.auth.v1.AuthResponse"> & {
  /**
   * @generated from field: gargauth.auth.v1.Correlation correlation = 1;
   */
  correlation?: Correlation;

  /**
   * @generated from oneof gargauth.auth.v1.AuthResponse.result
   */
  result: {
    /**
     * @generated from field: gargauth.auth.v1.AuthSuccessful success = 2;
     */
    value: AuthSuccessful;
    case: "success";
  } | {
    /**
     * @generated from field: gargauth.auth.v1.AuthFailure failure = 3;
     */
    value: AuthFailure;
    case: "failure";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gargauth.auth.v1.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_auth_response, 0);

