// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Client } from "./client_pb";
import { file_gargauth_auth_v1_client } from "./client_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/authenticate_consumer_request.proto.
 */
export const file_gargauth_auth_v1_authenticate_consumer_request: GenFile = /*@__PURE__*/
  fileDesc("CjRnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lcl9yZXF1ZXN0LnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIlgKG0F1dGhlbnRpY2F0ZUNvbnN1bWVyUmVxdWVzdBIoCgZjbGllbnQYASABKAsyGC5nYXJnYXV0aC5hdXRoLnYxLkNsaWVudBIPCgdwYXlsb2FkGAIgASgMQpoBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIgQXV0aGVudGljYXRlQ29uc3VtZXJSZXF1ZXN0UHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [file_gargauth_auth_v1_client]);

/**
 * @generated from message gargauth.auth.v1.AuthenticateConsumerRequest
 */
export type AuthenticateConsumerRequest = Message<"gargauth.auth.v1.AuthenticateConsumerRequest"> & {
  /**
   * @generated from field: gargauth.auth.v1.Client client = 1;
   */
  client?: Client;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.AuthenticateConsumerRequest.
 * Use `create(AuthenticateConsumerRequestSchema)` to create a new message.
 */
export const AuthenticateConsumerRequestSchema: GenMessage<AuthenticateConsumerRequest> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_authenticate_consumer_request, 0);

