// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Correlation } from "./correlation_pb";
import { file_gargauth_auth_v1_correlation } from "./correlation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/auth_request.proto.
 */
export const file_gargauth_auth_v1_auth_request: GenFile = /*@__PURE__*/
  fileDesc("CiNnYXJnYXV0aC9hdXRoL3YxL2F1dGhfcmVxdWVzdC5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSKJAQoLQXV0aFJlcXVlc3QSMgoLY29ycmVsYXRpb24YASABKAsyHS5nYXJnYXV0aC5hdXRoLnYxLkNvcnJlbGF0aW9uEg4KBmtleV9pZBgCIAEoDBIRCgljbGllbnRfaWQYAyABKAwSEgoKcHVibGljX2tleRgEIAEoDBIPCgdwYXlsb2FkGAUgASgMQooBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIQQXV0aFJlcXVlc3RQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [file_gargauth_auth_v1_correlation]);

/**
 * @generated from message gargauth.auth.v1.AuthRequest
 */
export type AuthRequest = Message<"gargauth.auth.v1.AuthRequest"> & {
  /**
   * @generated from field: gargauth.auth.v1.Correlation correlation = 1;
   */
  correlation?: Correlation;

  /**
   * @generated from field: bytes key_id = 2;
   */
  keyId: Uint8Array;

  /**
   * @generated from field: bytes client_id = 3;
   */
  clientId: Uint8Array;

  /**
   * @generated from field: bytes public_key = 4;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: bytes payload = 5;
   */
  payload: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.AuthRequest.
 * Use `create(AuthRequestSchema)` to create a new message.
 */
export const AuthRequestSchema: GenMessage<AuthRequest> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_auth_request, 0);

