// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_failure.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/auth_failure.proto.
 */
export const file_gargauth_auth_v1_auth_failure: GenFile = /*@__PURE__*/
  fileDesc("CiNnYXJnYXV0aC9hdXRoL3YxL2F1dGhfZmFpbHVyZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSINCgtBdXRoRmFpbHVyZUKKAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEEF1dGhGYWlsdXJlUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");

/**
 * @generated from message gargauth.auth.v1.AuthFailure
 */
export type AuthFailure = Message<"gargauth.auth.v1.AuthFailure"> & {
};

/**
 * Describes the message gargauth.auth.v1.AuthFailure.
 * Use `create(AuthFailureSchema)` to create a new message.
 */
export const AuthFailureSchema: GenMessage<AuthFailure> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_auth_failure, 0);

