// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer_response.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ConsumerAuthSuccessful } from "./consumer/consumer_auth_successful_pb";
import { file_gargauth_auth_v1_consumer_consumer_auth_successful } from "./consumer/consumer_auth_successful_pb";
import type { ConsumerAuthFailure } from "./consumer/consumer_auth_failure_pb";
import { file_gargauth_auth_v1_consumer_consumer_auth_failure } from "./consumer/consumer_auth_failure_pb";
import type { Correlation } from "./correlation_pb";
import { file_gargauth_auth_v1_correlation } from "./correlation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/authenticate_consumer_response.proto.
 */
export const file_gargauth_auth_v1_authenticate_consumer_response: GenFile = /*@__PURE__*/
  fileDesc("CjVnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lcl9yZXNwb25zZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSLTAQocQXV0aGVudGljYXRlQ29uc3VtZXJSZXNwb25zZRIyCgtjb3JyZWxhdGlvbhgBIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb24SOwoHc3VjY2VzcxgCIAEoCzIoLmdhcmdhdXRoLmF1dGgudjEuQ29uc3VtZXJBdXRoU3VjY2Vzc2Z1bEgAEjgKB2ZhaWx1cmUYAyABKAsyJS5nYXJnYXV0aC5hdXRoLnYxLkNvbnN1bWVyQXV0aEZhaWx1cmVIAEIICgZyZXN1bHRCmwEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQiFBdXRoZW50aWNhdGVDb25zdW1lclJlc3BvbnNlUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [file_gargauth_auth_v1_consumer_consumer_auth_successful, file_gargauth_auth_v1_consumer_consumer_auth_failure, file_gargauth_auth_v1_correlation]);

/**
 * @generated from message gargauth.auth.v1.AuthenticateConsumerResponse
 */
export type AuthenticateConsumerResponse = Message<"gargauth.auth.v1.AuthenticateConsumerResponse"> & {
  /**
   * @generated from field: gargauth.auth.v1.Correlation correlation = 1;
   */
  correlation?: Correlation;

  /**
   * @generated from oneof gargauth.auth.v1.AuthenticateConsumerResponse.result
   */
  result: {
    /**
     * @generated from field: gargauth.auth.v1.ConsumerAuthSuccessful success = 2;
     */
    value: ConsumerAuthSuccessful;
    case: "success";
  } | {
    /**
     * @generated from field: gargauth.auth.v1.ConsumerAuthFailure failure = 3;
     */
    value: ConsumerAuthFailure;
    case: "failure";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gargauth.auth.v1.AuthenticateConsumerResponse.
 * Use `create(AuthenticateConsumerResponseSchema)` to create a new message.
 */
export const AuthenticateConsumerResponseSchema: GenMessage<AuthenticateConsumerResponse> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_authenticate_consumer_response, 0);

