"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer_response.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthenticateConsumerResponseSchema = exports.file_gargauth_auth_v1_authenticate_consumer_response = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
var consumer_auth_successful_pb_1 = require("./consumer/consumer_auth_successful_pb");
var consumer_auth_failure_pb_1 = require("./consumer/consumer_auth_failure_pb");
var correlation_pb_1 = require("./correlation_pb");
/**
 * Describes the file gargauth/auth/v1/authenticate_consumer_response.proto.
 */
exports.file_gargauth_auth_v1_authenticate_consumer_response = (0, codegenv1_1.fileDesc)("CjVnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lcl9yZXNwb25zZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSLTAQocQXV0aGVudGljYXRlQ29uc3VtZXJSZXNwb25zZRIyCgtjb3JyZWxhdGlvbhgBIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb24SOwoHc3VjY2VzcxgCIAEoCzIoLmdhcmdhdXRoLmF1dGgudjEuQ29uc3VtZXJBdXRoU3VjY2Vzc2Z1bEgAEjgKB2ZhaWx1cmUYAyABKAsyJS5nYXJnYXV0aC5hdXRoLnYxLkNvbnN1bWVyQXV0aEZhaWx1cmVIAEIICgZyZXN1bHRCmwEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQiFBdXRoZW50aWNhdGVDb25zdW1lclJlc3BvbnNlUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [consumer_auth_successful_pb_1.file_gargauth_auth_v1_consumer_consumer_auth_successful, consumer_auth_failure_pb_1.file_gargauth_auth_v1_consumer_consumer_auth_failure, correlation_pb_1.file_gargauth_auth_v1_correlation]);
/**
 * Describes the message gargauth.auth.v1.AuthenticateConsumerResponse.
 * Use `create(AuthenticateConsumerResponseSchema)` to create a new message.
 */
exports.AuthenticateConsumerResponseSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_authenticate_consumer_response, 0);
