// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/authenticate_consumer.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { AuthRequestSchema } from "./auth_request_pb";
import { file_gargauth_auth_v1_auth_request } from "./auth_request_pb";
import type { AuthResponseSchema } from "./auth_response_pb";
import { file_gargauth_auth_v1_auth_response } from "./auth_response_pb";

/**
 * Describes the file gargauth/auth/v1/authenticate_consumer.proto.
 */
export const file_gargauth_auth_v1_authenticate_consumer: GenFile = /*@__PURE__*/
  fileDesc("CixnYXJnYXV0aC9hdXRoL3YxL2F1dGhlbnRpY2F0ZV9jb25zdW1lci5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MTJsChtBdXRoZW50aWNhdGVDb25zdW1lclNlcnZpY2USTQoMYXV0aGVudGljYXRlEh0uZ2FyZ2F1dGguYXV0aC52MS5BdXRoUmVxdWVzdBoeLmdhcmdhdXRoLmF1dGgudjEuQXV0aFJlc3BvbnNlQpMBChRjb20uZ2FyZ2F1dGguYXV0aC52MUIZQXV0aGVudGljYXRlQ29uc3VtZXJQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [file_gargauth_auth_v1_auth_request, file_gargauth_auth_v1_auth_response]);

/**
 * @generated from service gargauth.auth.v1.AuthenticateConsumerService
 */
export const AuthenticateConsumerService: GenService<{
  /**
   * @generated from rpc gargauth.auth.v1.AuthenticateConsumerService.authenticate
   */
  authenticate: {
    methodKind: "unary";
    input: typeof AuthRequestSchema;
    output: typeof AuthResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gargauth_auth_v1_authenticate_consumer, 0);

