"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/auth_failure.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthFailureSchema = exports.file_gargauth_auth_v1_auth_failure = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/auth_failure.proto.
 */
exports.file_gargauth_auth_v1_auth_failure = (0, codegenv1_1.fileDesc)("CiNnYXJnYXV0aC9hdXRoL3YxL2F1dGhfZmFpbHVyZS5wcm90bxIQZ2FyZ2F1dGguYXV0aC52MSINCgtBdXRoRmFpbHVyZUKKAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEEF1dGhGYWlsdXJlUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");
/**
 * Describes the message gargauth.auth.v1.AuthFailure.
 * Use `create(AuthFailureSchema)` to create a new message.
 */
exports.AuthFailureSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_auth_failure, 0);
