// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/client_init_request.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Client } from "./client_pb";
import { file_gargauth_auth_v1_client } from "./client_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/client_init_request.proto.
 */
export const file_gargauth_auth_v1_client_init_request: GenFile = /*@__PURE__*/
  fileDesc("CipnYXJnYXV0aC9hdXRoL3YxL2NsaWVudF9pbml0X3JlcXVlc3QucHJvdG8SEGdhcmdhdXRoLmF1dGgudjEiTgoRQ2xpZW50SW5pdFJlcXVlc3QSKAoGY2xpZW50GAEgASgLMhguZ2FyZ2F1dGguYXV0aC52MS5DbGllbnQSDwoHcGF5bG9hZBgCIAEoDEKQAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCFkNsaWVudEluaXRSZXF1ZXN0UHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z", [file_gargauth_auth_v1_client]);

/**
 * @generated from message gargauth.auth.v1.ClientInitRequest
 */
export type ClientInitRequest = Message<"gargauth.auth.v1.ClientInitRequest"> & {
  /**
   * @generated from field: gargauth.auth.v1.Client client = 1;
   */
  client?: Client;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.ClientInitRequest.
 * Use `create(ClientInitRequestSchema)` to create a new message.
 */
export const ClientInitRequestSchema: GenMessage<ClientInitRequest> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_client_init_request, 0);

