// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/client_init_response.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Correlation } from "./correlation_pb";
import { file_gargauth_auth_v1_correlation } from "./correlation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/client_init_response.proto.
 */
export const file_gargauth_auth_v1_client_init_response: GenFile = /*@__PURE__*/
  fileDesc("CitnYXJnYXV0aC9hdXRoL3YxL2NsaWVudF9pbml0X3Jlc3BvbnNlLnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIkgKEkNsaWVudEluaXRSZXNwb25zZRIyCgtjb3JyZWxhdGlvbhgBIAEoCzIdLmdhcmdhdXRoLmF1dGgudjEuQ29ycmVsYXRpb25CkQEKFGNvbS5nYXJnYXV0aC5hdXRoLnYxQhdDbGllbnRJbml0UmVzcG9uc2VQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [file_gargauth_auth_v1_correlation]);

/**
 * @generated from message gargauth.auth.v1.ClientInitResponse
 */
export type ClientInitResponse = Message<"gargauth.auth.v1.ClientInitResponse"> & {
  /**
   * @generated from field: gargauth.auth.v1.Correlation correlation = 1;
   */
  correlation?: Correlation;
};

/**
 * Describes the message gargauth.auth.v1.ClientInitResponse.
 * Use `create(ClientInitResponseSchema)` to create a new message.
 */
export const ClientInitResponseSchema: GenMessage<ClientInitResponse> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_client_init_response, 0);

