// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/correlation.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gargauth/auth/v1/correlation.proto.
 */
export const file_gargauth_auth_v1_correlation: GenFile = /*@__PURE__*/
  fileDesc("CiJnYXJnYXV0aC9hdXRoL3YxL2NvcnJlbGF0aW9uLnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIhoKC0NvcnJlbGF0aW9uEgsKA3VpZBgBIAEoDEKKAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEENvcnJlbGF0aW9uUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");

/**
 * @generated from message gargauth.auth.v1.Correlation
 */
export type Correlation = Message<"gargauth.auth.v1.Correlation"> & {
  /**
   * @generated from field: bytes uid = 1;
   */
  uid: Uint8Array;
};

/**
 * Describes the message gargauth.auth.v1.Correlation.
 * Use `create(CorrelationSchema)` to create a new message.
 */
export const CorrelationSchema: GenMessage<Correlation> = /*@__PURE__*/
  messageDesc(file_gargauth_auth_v1_correlation, 0);

