"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/correlation.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CorrelationSchema = exports.file_gargauth_auth_v1_correlation = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file gargauth/auth/v1/correlation.proto.
 */
exports.file_gargauth_auth_v1_correlation = (0, codegenv1_1.fileDesc)("CiJnYXJnYXV0aC9hdXRoL3YxL2NvcnJlbGF0aW9uLnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxIhoKC0NvcnJlbGF0aW9uEgsKA3VpZBgBIAEoDEKKAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCEENvcnJlbGF0aW9uUHJvdG9QAaICA0dBWKoCEEdhcmdhdXRoLkF1dGguVjHKAhBHYXJnYXV0aFxBdXRoXFYx4gIcR2FyZ2F1dGhcQXV0aFxWMVxHUEJNZXRhZGF0YeoCEkdhcmdhdXRoOjpBdXRoOjpWMWIGcHJvdG8z");
/**
 * Describes the message gargauth.auth.v1.Correlation.
 * Use `create(CorrelationSchema)` to create a new message.
 */
exports.CorrelationSchema = (0, codegenv1_1.messageDesc)(exports.file_gargauth_auth_v1_correlation, 0);
