// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/init_client.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { ClientInitRequestSchema } from "./client_init_request_pb";
import { file_gargauth_auth_v1_client_init_request } from "./client_init_request_pb";
import type { ClientInitResponseSchema } from "./client_init_response_pb";
import { file_gargauth_auth_v1_client_init_response } from "./client_init_response_pb";

/**
 * Describes the file gargauth/auth/v1/init_client.proto.
 */
export const file_gargauth_auth_v1_init_client: GenFile = /*@__PURE__*/
  fileDesc("CiJnYXJnYXV0aC9hdXRoL3YxL2luaXRfY2xpZW50LnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxMm4KEUluaXRDbGllbnRTZXJ2aWNlElkKDGF1dGhlbnRpY2F0ZRIjLmdhcmdhdXRoLmF1dGgudjEuQ2xpZW50SW5pdFJlcXVlc3QaJC5nYXJnYXV0aC5hdXRoLnYxLkNsaWVudEluaXRSZXNwb25zZUKJAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCD0luaXRDbGllbnRQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [file_gargauth_auth_v1_client_init_request, file_gargauth_auth_v1_client_init_response]);

/**
 * @generated from service gargauth.auth.v1.InitClientService
 */
export const InitClientService: GenService<{
  /**
   * @generated from rpc gargauth.auth.v1.InitClientService.authenticate
   */
  authenticate: {
    methodKind: "unary";
    input: typeof ClientInitRequestSchema;
    output: typeof ClientInitResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gargauth_auth_v1_init_client, 0);

