"use strict";
// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file gargauth/auth/v1/init_client.proto (package gargauth.auth.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InitClientService = exports.file_gargauth_auth_v1_init_client = void 0;
var codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
var client_init_request_pb_1 = require("./client_init_request_pb");
var client_init_response_pb_1 = require("./client_init_response_pb");
/**
 * Describes the file gargauth/auth/v1/init_client.proto.
 */
exports.file_gargauth_auth_v1_init_client = (0, codegenv1_1.fileDesc)("CiJnYXJnYXV0aC9hdXRoL3YxL2luaXRfY2xpZW50LnByb3RvEhBnYXJnYXV0aC5hdXRoLnYxMm4KEUluaXRDbGllbnRTZXJ2aWNlElkKDGF1dGhlbnRpY2F0ZRIjLmdhcmdhdXRoLmF1dGgudjEuQ2xpZW50SW5pdFJlcXVlc3QaJC5nYXJnYXV0aC5hdXRoLnYxLkNsaWVudEluaXRSZXNwb25zZUKJAQoUY29tLmdhcmdhdXRoLmF1dGgudjFCD0luaXRDbGllbnRQcm90b1ABogIDR0FYqgIQR2FyZ2F1dGguQXV0aC5WMcoCEEdhcmdhdXRoXEF1dGhcVjHiAhxHYXJnYXV0aFxBdXRoXFYxXEdQQk1ldGFkYXRh6gISR2FyZ2F1dGg6OkF1dGg6OlYxYgZwcm90bzM", [client_init_request_pb_1.file_gargauth_auth_v1_client_init_request, client_init_response_pb_1.file_gargauth_auth_v1_client_init_response]);
/**
 * @generated from service gargauth.auth.v1.InitClientService
 */
exports.InitClientService = (0, codegenv1_1.serviceDesc)(exports.file_gargauth_auth_v1_init_client, 0);
